### ISSUE TITLE
pondering option freezing problem with Ryzen

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#66]
When I used i7-3770K, there was no problem with pondering option.

But in the Ryzen-1700@3.7Ghz, there is a freezing if I use pondering option.

**Comment by zakki** [comment]
Could you try `--no-nn` option and original koban6's Ray https://github.com/koban6/Ray to specify which part is wrong?

**Comment by crayzok** [comment]
Wow after I try --no-nn option, it is fixed!

Before I try --no-nn option, I have faced that error message whenever I use --pondering option.

![1](https://user-images.githubusercontent.com/13972495/27287753-ace41c98-553f-11e7-9bcb-b2dba9413529.jpg)

**Comment by crayzok** [comment]
-no-nn option means not use training data and only depends on monte carlo?

![ff](https://user-images.githubusercontent.com/13972495/27289015-75e1e6c2-5543-11e7-8e06-dad41725b628.jpg)

**Comment by zakki** [comment]
Yes, it don't use.
So perhaps Rn's extended part or cntk or gpu causes freeze.

**Comment by craytok** [comment]
I guess --pondering option got error and freezed when thinking time is too short (0.022sec, 0.068sec)

If it's right, you can set minimum thinking time(0.1s or 1s) by lag buffer.

**Comment by crayzok** [comment]
it may be bottleneck...? my CPU is Ryzen1700@3.7ghz and GPU is GTX1060 3gb...

I used 16threads option.

**Comment by zakki** [comment]
It seems that Pascal Titan X can handle only 3 or 4 search thread on  i7-6700K.
And I found the bug that only 1st thread wait for GPU, and other threads en queue, and with pondering Rn blocks until all queued evaluation done.
https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L1438

This means evaluation queue get bigger and bigger while pondering, if CPU is too fast.
So, with pondering and long time-setting, Rn uses very long time to handle all queued evaluation after gogui interrupt pondering.

**Comment by zakki** [comment]
Fixed https://github.com/zakki/Ray/commit/d6cffb3eff79e390638cb3fcc4190dce6d8c4a7f
Many core CPU utilization is on TODO list.

**Comment by wpstmxhs** [comment]
I tried zakki's fix, and it seems weaker than before.
I have no idea about why it's weaker.

**Comment by zakki** [comment]
It lets CPU sleep to prevent long freeze and large memory usage.
It makes Rn weaker by design.

Rn has to use spare CPU in some way.

**Comment by crayzok** [comment]
Hi zakki. I compiled your recent source. (Ray-nn) 
And you were right. there is no difference between thread 4 and 15 (in Playout Speed).
Freezing problem(in Ryzen1700@3.7ghz) still exists in current source. 
(there was no freezing at intel 3770k with any options. even --thread 8)
The bug appears only when I set thread option more than 4.(From more than 5threads)
I tried option (--thread 4 --tree-size 65536 --pondering --playout 50000) and (--thread 4 --tree-size 65536 --pondering --const-time 15). in this option, Playout Speed is 3600~4300PO/sec. and there was no freezing and any errors)

**Comment by crayzok** [comment]
But if I change option to (--thread 6 --tree-size 65536 --pondering --playout 50000 ) (--thread 6 --tree-size 65536 --pondering --const-time 15), Freezing(about 5sec) or Error happens. Playout Speed is 3800-4300 PO/sec (with 100,000~500,000 pondering data)

**Comment by zakki** [comment]
Perhaps I need to call WaitForEvaluationQueue() in ParallelUctSearchPondering too. I'll fix at next version.

**Comment by zakki** [comment]
@crayzok I think rn-4.20.4 fixed this issue.
